### ISSUE TITLE
cannot access I2C after soft reboot with UF2 bootloader

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/tinyuf2#74]
When the UF2 bootloader is installed on my metro-esp32s2 -- I am unable to access an I2C device after a soft reboot.
I can access after a hard reset but then it fails after a soft reboot if I try to access it again.

see issue at https://github.com/adafruit/circuitpython/issues/4147

The issue does not occur if I do not use the UF2 Bootloader on the Metro-esp32s2

**Comment by ladyada** [comment]
do ya have a logic analyzer trace of the scl/sda lines? it may be illuminating

**Comment by jerryneedell** [comment]
Yes -- I'll see what I can find.

**Comment by jerryneedell** [comment]
With UF2 bootloader -- this is a "normal" I2C accessing the SHTC3 sensor
![esp32s2_normal_i2c](https://user-images.githubusercontent.com/15856834/107677583-6f061400-6c68-11eb-8a67-783e765273c8.png)

This is the failed aces after a soft reboot -- no activity on SDA

![esp32s2_fail_i2c](https://user-images.githubusercontent.com/15856834/107677584-6f9eaa80-6c68-11eb-87ff-a893e341a512.png)

**Comment by ladyada** [comment]
what the...?

**Comment by ladyada** [comment]
wanna see if you can query the i2c SDA pin mux? thats the only thing i can imagine it is

**Comment by jerryneedell** [comment]
Can you give some instructions. I don't understand what you are asking for. sorry...

**Comment by ladyada** [comment]
lets wait till @hathach is back from TET holiday - could you verify that the other 'weird i2c issues' with esp32s2 in circuitpython are resolved when uf2 is not used?

**Comment by jerryneedell** [comment]
I'll take a look.

**Comment by jerryneedell** [comment]
The issue with the  mcp9600 https://github.com/adafruit/circuitpython/issues/3894
occurs on my metro-esp32s2 even without the UF2 bootloader so does not appear to be related.
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Adafruit Metro ESP32S2 with ESP32S2
>>> import mcp9600_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcp9600_simpletest.py", line 12, in <module>
  File "adafruit_mcp9600.py", line 178, in __init__
  File "adafruit_mcp9600.py", line 178, in __init__
OSError: [Errno 19] Unsupported operation
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.


Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Adafruit Metro ESP32S2 with ESP32S2
>>> import mcp9600_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcp9600_simpletest.py", line 12, in <module>
  File "adafruit_mcp9600.py", line 165, in __init__
ValueError: No I2C device at address: 67
>>> 


```

**Comment by jerryneedell** [comment]
the test code in https://github.com/adafruit/circuitpython/issues/4046  also causes a crash - drop USB and resets
```
import board
import busio
print(dir(board))
i2c = busio.I2C(board.SCL, board.SDA)

def printdevices():
    i2c.try_lock()
    # Find the I2C devices available.
    devices = i2c.scan()
    print("I2C devices:", len(devices))
    for device in devices:
        print(hex(device))
    i2c.unlock()
    print("I2C unlocked! ")

printdevices()
```

**Comment by ladyada** [comment]
mcp9600 is a bad chip to use for testing, use something that is 'normal' acting

**Comment by jerryneedell** [comment]
> mcp9600 is a bad chip to use for testing, use something that is 'normal' acting

Agreed! I was just trying to reproduce the issue. So far, not having issues with other boards - shtc3 or bme680

**Comment by makermelissa** [comment]
Hello, I think I figured out something in regards to this. I hooked up a project that used a bme280 and pm25 sensor (to a MagTag). It always worked fine when I initialized the pm25 sensor first, but failed as described when I did the bme280 sensor. I noticed in the library that the main difference between the init of the drivers is the pm25 is attempted to be probed multiple times and the bme280 is attempted to only be probed once. I made a local change in my bme280 lib to attempt multiple times as well and it consistently worked.

So I hooked up a logic analyzer and it appears to consistently need 2 probes to start communicating. Here are the logic analyzer screenshots.
At a high level, here's what it looks like:
![Screen Shot 2021-02-19 at 10 16 11 AM](https://user-images.githubusercontent.com/2681417/108546019-654e6300-729d-11eb-840b-819fd79afe47.png)

The first blip looks like this. I think it's just i2c being set up or something.
![Screen Shot 2021-02-19 at 10 18 51 AM](https://user-images.githubusercontent.com/2681417/108546093-7f884100-729d-11eb-9e3e-1ba3f8f69dde.png)

Next it does 2 of these. I think this is the probe because I had a delay in there originally (which turned out to be unnecessary) and that altered the time between these packets.
![Screen Shot 2021-02-19 at 10 16 59 AM](https://user-images.githubusercontent.com/2681417/108546171-99298880-729d-11eb-86b0-74731c595fcd.png)

After that, the chip responds just fine.

**Comment by makermelissa** [comment]
This may be more circuitpython related though.

**Comment by hathach** [comment]
I guess this is fixed now in circuitpython and safe to close, right ?

**Comment by makermelissa** [comment]
I think it should probably be re-tested first. @jerryneedell did you want to try re-testing? I don't have the sensors with me at the moment.

**Comment by hathach** [comment]
quick check, could we close this now ? @makermelissa @jerryneedell

**Comment by makermelissa** [comment]
I'm pretty sure this isn't an issue anymore. We can always re-open if it is.

**Comment by jerryneedell** [comment]
Thanks! For some reason, I never saw the earlier prompts to me. Sorry. I was not ignoring you!

**Comment by hathach** [comment]
No problem at all. I forgot about this as well :)
